image:
  repository: microservices
  tag: ""
  pullPolicy: IfNotPresent

containerPort: 8080

defaultResources:
  requests:
    memory: 1Gi
  limits:
    memory: 2Gi

services:
  api:
    command: ["./api"]
    replicaCount: 3
    service:
      type: LoadBalancer
      port: 8080
    env:
      BOOKS_API_HOST: books
      MOVIES_API_HOST: movies

  books:
    command: ["./books"]
    replicaCount: 3
    service:
      type: ClusterIP
      port: 80

  movies:
    command: ["./movies"]
    replicaCount: 3
    service:
      type: ClusterIP
      port: 80

limitRange:
  enabled: true
  name: microservices-limits
  limits:
    - type: Container

resourceQuota:
  enabled: true
  name: microservices-quota
  hard:
    requests.memory: 1Gi
  # Si le pods va au dessus de 2gi, il est kill automatiquement
    limits.memory: 2Gi
  # Compte 12 pods au max,
  # dû au rolling update qui pourrait rajouter un pod pour chaque services.
    pods: "12"
