{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.limitRange.name }}
spec:
  limits:
    {{- toYaml .Values.limitRange.limits | nindent 4 }}
{{- end }}
