apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: api
              topologyKey: zone
      topologySpreadConstraints:
         - maxSkew: 1
           topologyKey: kubernetes.io/hostname   # ← on cible le nœud physique/logique
           whenUnsatisfiable: ScheduleAnyway     # ← OPTIONNEL : si impossible, on schedule quand même
           labelSelector:                        # ← on cible TOUTES les apps
            matchExpressions:
              - key: app
                operator: Exists                # ← tous les pods qui ont une label "app"
      containers:
        - name: api
          image: microservices:1.0
          command: ["./api"]
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: BOOKS_API_HOST
              value: "books"
            - name: MOVIES_API_HOST
              value: "movies"
          ports:
            - containerPort: 8080
